title = 'Opensociety'
baseURL = 'https://opensoc1ety.github.io/'

defaultContentLanguage = 'en'
languageCode = 'en-us'

googleAnalytics = ''

enableGitInfo = true

markup.highlight.noClasses = false

theme='docura'
