description = 'A group of programmers/developers.'

author = 'Opensociety'
authorURL = 'https://github.com/opensoc1ety'

currentYear = 2023
# projectStartYear = 2020

# facebookURL = 'https://facebook.com/asdff'
# twitterURL = 'https://www.twitter.com/'
# githubURL = 'https://github.com/'
# youtubeURL = 'https://www.youtube.com/'

githubRepo = 'opensoc1ety/opensoc1ety.github.io'
# githubSponsorURL = 'https://github.com/sponsors/'
# buyMeACoffeeURL = 'https://www.buymeacoffee.com/'

[algolia]
[algolia.en]
container = '#site-header-search'
appId = ''
indexName = ''
apiKey = ''

#googleAdClient = "ca-pub-XXXXXXXXXXXXXXXX"

#[[githubRepos]]
#name = 'Website'
#repo = 'docura/site'
#icon = "<i class='icon icon-book'></i>"
#description = 'The repository of the website.'
#
#[[githubRepos]]
#name = 'Code'
#repo = 'docura/docura'
#icon = "<i class='icon icon-theme'></i>"
#description = 'The repository of the theme.'
